.\" $Header: /var/lib/gforge/chroot/home/users/madduck/cvsroot.logcheck/debian/Attic/logcheck.8,v 1.1 2004/04/19 18:22:05 ttroxell Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "Logcheck" "8" 
.SH "NAME" 
logcheck \(em program to scan system logs for interesting lines 
.SH "SYNOPSIS" 
.PP 
\fBlogcheck\fR [\fBOPTIONS\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBlogcheck\fR command. 
.PP 
\fBlogcheck\fR is a program that scan system 
logs and mails a report. 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax. A 
summary of options is included below. 
.IP "\fB-c CFG\fP         " 10 
Overrule default configuration file. 
.IP "\fB-d\fP         " 10 
debug mode. 
.IP "\fB-h\fP         " 10 
Show usage information. 
.IP "\fB-l LOG\fP         " 10 
Overrule default logfile 
.IP "\fB-o\fP         " 10 
STDOUT mode, not sending mail 
.IP "\fB-p\fP         " 10 
Set the report level to "paranoid" 
.IP "\fB-r DIR\fP         " 10 
Overrule default rules directory 
.IP "\fB-R\fP         " 10 
Adds "Reboot:" to the email subject line 
.IP "\fB-s\fP         " 10 
Set the report level to "server" 
.IP "\fB-S DIR\fP         " 10 
Overrule default state directory 
.IP "\fB-t\fP         " 10 
Do not remove the TMPDIR 
.IP "\fB-w\fP         " 10 
Set the report level to "workstation" 
.SH "AUTHOR" 
.PP 
This manual page was written by Jon Middleton 
.\" created by instant / docbook-to-man, Thu 01 Apr 2004, 11:15 
